// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	model "github.com/godbobo/fast_ship/server/internal/model"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for IssueRecommendationStatus.
const (
	Active   IssueRecommendationStatus = "active"
	Deferred IssueRecommendationStatus = "deferred"
)

// Valid indicates whether the value is a known member of the IssueRecommendationStatus enum.
func (e IssueRecommendationStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Deferred:
		return true
	default:
		return false
	}
}

// Defines values for UpdateIssueRequestStateReason.
const (
	UpdateIssueRequestStateReasonCompleted  UpdateIssueRequestStateReason = "completed"
	UpdateIssueRequestStateReasonNotPlanned UpdateIssueRequestStateReason = "not_planned"
	UpdateIssueRequestStateReasonReopened   UpdateIssueRequestStateReason = "reopened"
)

// Valid indicates whether the value is a known member of the UpdateIssueRequestStateReason enum.
func (e UpdateIssueRequestStateReason) Valid() bool {
	switch e {
	case UpdateIssueRequestStateReasonCompleted:
		return true
	case UpdateIssueRequestStateReasonNotPlanned:
		return true
	case UpdateIssueRequestStateReasonReopened:
		return true
	default:
		return false
	}
}

// Defines values for VersionShipHooksStatus.
const (
	VersionShipHooksStatusCompleted  VersionShipHooksStatus = "completed"
	VersionShipHooksStatusFailed     VersionShipHooksStatus = "failed"
	VersionShipHooksStatusIncomplete VersionShipHooksStatus = "incomplete"
	VersionShipHooksStatusPending    VersionShipHooksStatus = "pending"
)

// Valid indicates whether the value is a known member of the VersionShipHooksStatus enum.
func (e VersionShipHooksStatus) Valid() bool {
	switch e {
	case VersionShipHooksStatusCompleted:
		return true
	case VersionShipHooksStatusFailed:
		return true
	case VersionShipHooksStatusIncomplete:
		return true
	case VersionShipHooksStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListIssuesParamsWorkflowStatus.
const (
	ListIssuesParamsWorkflowStatusDone       ListIssuesParamsWorkflowStatus = "done"
	ListIssuesParamsWorkflowStatusInProgress ListIssuesParamsWorkflowStatus = "in_progress"
	ListIssuesParamsWorkflowStatusTodo       ListIssuesParamsWorkflowStatus = "todo"
	ListIssuesParamsWorkflowStatusUnset      ListIssuesParamsWorkflowStatus = "unset"
)

// Valid indicates whether the value is a known member of the ListIssuesParamsWorkflowStatus enum.
func (e ListIssuesParamsWorkflowStatus) Valid() bool {
	switch e {
	case ListIssuesParamsWorkflowStatusDone:
		return true
	case ListIssuesParamsWorkflowStatusInProgress:
		return true
	case ListIssuesParamsWorkflowStatusTodo:
		return true
	case ListIssuesParamsWorkflowStatusUnset:
		return true
	default:
		return false
	}
}

// Defines values for ListIssuesParamsSort.
const (
	CommentsAsc  ListIssuesParamsSort = "comments_asc"
	CommentsDesc ListIssuesParamsSort = "comments_desc"
	CreatedAsc   ListIssuesParamsSort = "created_asc"
	CreatedDesc  ListIssuesParamsSort = "created_desc"
	UpdatedAsc   ListIssuesParamsSort = "updated_asc"
	UpdatedDesc  ListIssuesParamsSort = "updated_desc"
)

// Valid indicates whether the value is a known member of the ListIssuesParamsSort enum.
func (e ListIssuesParamsSort) Valid() bool {
	switch e {
	case CommentsAsc:
		return true
	case CommentsDesc:
		return true
	case CreatedAsc:
		return true
	case CreatedDesc:
		return true
	case UpdatedAsc:
		return true
	case UpdatedDesc:
		return true
	default:
		return false
	}
}

// Defines values for CountIssuesParamsWorkflowStatus.
const (
	CountIssuesParamsWorkflowStatusDone       CountIssuesParamsWorkflowStatus = "done"
	CountIssuesParamsWorkflowStatusInProgress CountIssuesParamsWorkflowStatus = "in_progress"
	CountIssuesParamsWorkflowStatusTodo       CountIssuesParamsWorkflowStatus = "todo"
	CountIssuesParamsWorkflowStatusUnset      CountIssuesParamsWorkflowStatus = "unset"
)

// Valid indicates whether the value is a known member of the CountIssuesParamsWorkflowStatus enum.
func (e CountIssuesParamsWorkflowStatus) Valid() bool {
	switch e {
	case CountIssuesParamsWorkflowStatusDone:
		return true
	case CountIssuesParamsWorkflowStatusInProgress:
		return true
	case CountIssuesParamsWorkflowStatusTodo:
		return true
	case CountIssuesParamsWorkflowStatusUnset:
		return true
	default:
		return false
	}
}

// Defines values for ListLogEntriesParamsSort.
const (
	TimestampAsc  ListLogEntriesParamsSort = "timestamp_asc"
	TimestampDesc ListLogEntriesParamsSort = "timestamp_desc"
)

// Valid indicates whether the value is a known member of the ListLogEntriesParamsSort enum.
func (e ListLogEntriesParamsSort) Valid() bool {
	switch e {
	case TimestampAsc:
		return true
	case TimestampDesc:
		return true
	default:
		return false
	}
}

// AISettings defines model for AISettings.
type AISettings struct {
	// ApiHost 默认 https://api.minimaxi.com
	ApiHost string `json:"api_host"`

	// Configured 是否已配置 API Key（Key 本身永不回显）
	Configured bool `json:"configured"`

	// Model 默认 MiniMax-M2.5
	Model string `json:"model"`

	// UpdatedAt omitempty，未配置时缺省
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`

	// KeyHash Key 的 SHA-256 哈希
	KeyHash string `json:"key_hash"`

	// KeyPrefix Key 原文前 8 字符（不含 fsk_ 前缀），用于列表辨识
	KeyPrefix  string  `json:"key_prefix"`
	LastUsedAt *string `json:"last_used_at"`
	Name       string  `json:"name"`
	UserId     string  `json:"user_id"`
}

// ApiKeyCreated defines model for ApiKeyCreated.
type ApiKeyCreated struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`

	// Key 完整 API Key（fsk_ 前缀），仅创建响应中出现一次，服务端不存原文
	Key *string `json:"key,omitempty"`

	// KeyHash Key 的 SHA-256 哈希
	KeyHash string `json:"key_hash"`

	// KeyPrefix Key 原文前 8 字符（不含 fsk_ 前缀），用于列表辨识
	KeyPrefix  string  `json:"key_prefix"`
	LastUsedAt *string `json:"last_used_at"`
	Name       string  `json:"name"`
	UserId     string  `json:"user_id"`
}

// Artifact defines model for Artifact.
type Artifact struct {
	FileName   string `json:"file_name"`
	FileSize   int64  `json:"file_size"`
	Id         string `json:"id"`
	Platform   string `json:"platform"`
	UploadedAt string `json:"uploaded_at"`

	// UploadedBy 用户名或 "API Key: <name>"
	UploadedBy string `json:"uploaded_by"`
	VersionId  string `json:"version_id"`
}

// AttachIssuePullRequestRequest defines model for AttachIssuePullRequestRequest.
type AttachIssuePullRequestRequest struct {
	// Url GitHub PR 链接，形如 https://github.com/<owner>/<repo>/pull/<number>（允许 http、www 前缀与尾部 /files、query、fragment 等）；其他字段由服务端从 GitHub 拉取
	Url string `json:"url"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// RefreshToken fsr_ 开头，有效期默认 7 天
	RefreshToken string `json:"refresh_token"`

	// Token JWT access token（HS256，有效期见服务端 jwt.expire_hours，默认 24h）
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Branch defines model for Branch.
type Branch struct {
	Default bool   `json:"default"`
	Name    string `json:"name"`
	Sha     string `json:"sha"`
}

// CollabAuthorKind defines model for CollabAuthorKind.
type CollabAuthorKind = model.CollabAuthorKind

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	Name string `binding:"required,min=1,max=100" json:"name"`
}

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	// Body ≤200000 rune
	Body *string `json:"body,omitempty"`

	// ParentId 父文档 ID；须同项目，深度 ≤64
	ParentId *string `json:"parent_id,omitempty"`

	// Title trim 后 1-200 rune
	Title string `json:"title"`
}

// CreateIssueRequest defines model for CreateIssueRequest.
type CreateIssueRequest struct {
	// Body Markdown；引用 /api/issues/assets/{aid}/content 链接会在创建时挂载草稿附件
	Body   *string      `json:"body,omitempty"`
	Source *IssueSource `json:"source,omitempty"`

	// Title trim 后须非空
	Title string `json:"title"`

	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus *IssueWorkflowStatus `json:"workflow_status,omitempty"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description *string `json:"description,omitempty"`

	// GithubPrToken PR 访问 Token，仅用于读取关联 PR（可为其他仓库）；加密存储，不回显
	GithubPrToken *string `json:"github_pr_token,omitempty"`

	// GithubToken GitHub PAT（加密存储，不回显）
	GithubToken *string `json:"github_token,omitempty"`

	// Name 项目名，当前用户下唯一
	Name string `binding:"required,min=1,max=100" json:"name"`

	// RepositoryUrl GitHub 仓库链接（owner/repo 或完整 URL）；设置时须同时提供 github_token 或 source_project_id
	RepositoryUrl *string `json:"repository_url,omitempty"`

	// SourceProjectId 复用另一项目的 GitHub Token；优先于 github_token
	SourceProjectId *string `json:"source_project_id,omitempty"`
}

// CreateVersionRequest defines model for CreateVersionRequest.
type CreateVersionRequest struct {
	// ReleaseNotes Release 说明；发货前必填
	ReleaseNotes *string `json:"release_notes,omitempty"`

	// TargetCommitish 目标分支；非空时校验为仓库已存在分支
	TargetCommitish *string `json:"target_commitish,omitempty"`

	// VersionNumber 版本号（同 tag 名），项目内唯一
	VersionNumber string `binding:"required" json:"version_number"`
}

// DashboardDailyResolvedPoint defines model for DashboardDailyResolvedPoint.
type DashboardDailyResolvedPoint struct {
	// Date YYYY-MM-DD
	Date string `json:"date"`

	// Projects 当日无数据的项目不出现（可为 null/空）
	Projects      []DashboardDailyResolvedProjectPoint `json:"projects"`
	ResolvedCount int                                  `json:"resolved_count"`
}

// DashboardDailyResolvedProjectPoint defines model for DashboardDailyResolvedProjectPoint.
type DashboardDailyResolvedProjectPoint struct {
	Count       int    `json:"count"`
	ProjectId   string `json:"project_id"`
	ProjectName string `json:"project_name"`
}

// DashboardOverview defines model for DashboardOverview.
type DashboardOverview struct {
	// DailyResolved 固定近 30 天（含今天），逐日排列
	DailyResolved       []DashboardDailyResolvedPoint    `json:"daily_resolved"`
	OpenIssuesByProject []DashboardProjectOpenIssuePoint `json:"open_issues_by_project"`
}

// DashboardProjectOpenIssuePoint defines model for DashboardProjectOpenIssuePoint.
type DashboardProjectOpenIssuePoint struct {
	OpenIssueCount int    `json:"open_issue_count"`
	ProjectId      string `json:"project_id"`
	ProjectName    string `json:"project_name"`
}

// DeferIssueRecommendationRequest defines model for DeferIssueRecommendationRequest.
type DeferIssueRecommendationRequest struct {
	// Note 延后备注，trim 后 ≤500 rune；缺省或空串表示无备注
	Note *string `json:"note,omitempty"`
}

// Document defines model for Document.
type Document struct {
	Body      string  `json:"body"`
	CreatedAt string  `json:"created_at"`
	Id        string  `json:"id"`
	ParentId  *string `json:"parent_id"`
	ProjectId string  `json:"project_id"`
	Title     string  `json:"title"`
	UpdatedAt string  `json:"updated_at"`
}

// DocumentListItem defines model for DocumentListItem.
type DocumentListItem struct {
	CreatedAt string  `json:"created_at"`
	Id        string  `json:"id"`
	ParentId  *string `json:"parent_id"`
	ProjectId string  `json:"project_id"`
	Title     string  `json:"title"`
	UpdatedAt string  `json:"updated_at"`
}

// Envelope 统一 JSON 信封 {code, message, data}
type Envelope struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data 响应负载；形状随端点而变，由 allOf 组合的兄弟 schema 收窄
	Data interface{} `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ErrorEnvelope 错误响应信封
type ErrorEnvelope struct {
	// Code 业务错误码（4xxxx 按区间映射 HTTP 状态：401xx→401，403xx→403，404xx→404，409xx→409，412xx→412，50xxx→500；502xx→502）
	Code int `json:"code"`

	// Data 恒为 null
	Data    map[string]interface{} `json:"data"`
	Message string                 `json:"message"`
}

// GenerateTitleResponse defines model for GenerateTitleResponse.
type GenerateTitleResponse struct {
	// Titles 候选标题（通常 3 个）
	Titles []string `json:"titles"`
}

// Issue defines model for Issue.
type Issue struct {
	Author IssueActor `json:"author"`
	Body   string     `json:"body"`

	// BodyHtml github 来源为远端渲染 HTML（媒体链接经代理改写）；internal 为空串
	BodyHtml  string           `json:"body_html"`
	ClosedAt  *string          `json:"closed_at"`
	Collab    *IssueCollabArea `json:"collab,omitempty"`
	CreatedAt string           `json:"created_at"`

	// Github omitempty，仅 github 来源 Issue 出现
	Github *IssueGitHubMeta `json:"github,omitempty"`
	Id     string           `json:"id"`

	// InternalMeta omitempty；无 meta 且无 checklist 时整个字段缺省
	InternalMeta *IssueInternalMeta `json:"internal_meta,omitempty"`
	ProjectId    string             `json:"project_id"`

	// PullRequestSummary Issue 关联 PR 的聚合计数；closed 计数 = total - open - merged
	PullRequestSummary *IssuePullRequestSummary `json:"pull_request_summary,omitempty"`

	// PullRequests omitempty；仅 Issue 详情响应携带（读取失败或无关联时缺省）；列表项不出现
	PullRequests []IssuePullRequest `json:"pull_requests,omitempty"`

	// Reference 短编号；github 为 GH-<number>，internal 为 INT-<sequence_number>
	Reference string `json:"reference"`

	// SequenceNumber 项目内自增序号（reference 的 INT-n 来源）
	SequenceNumber int `json:"sequence_number"`

	// ShipHook omitempty；仅 Issue 详情/列表项中出现，未预约时缺省
	ShipHook *IssueShipHook `json:"ship_hook,omitempty"`
	Source   IssueSource    `json:"source"`
	State    IssueState     `json:"state"`

	// StateReason completed / not_planned / reopened 或空串
	StateReason string `json:"state_reason"`
	Title       string `json:"title"`

	// UnreadCommentsCount 未读评论数；仅列表响应填充（internal issue 恒为 0），详情响应恒为 0
	UnreadCommentsCount int    `json:"unread_comments_count"`
	UpdatedAt           string `json:"updated_at"`
}

// IssueActor defines model for IssueActor.
type IssueActor struct {
	// AvatarUrl GitHub 头像经媒体代理改写；internal 用户为空串
	AvatarUrl string `json:"avatar_url"`
	Login     string `json:"login"`
}

// IssueAsset defines model for IssueAsset.
type IssueAsset struct {
	// ContentUrl /api/issues/assets/{aid}/content
	ContentUrl string `json:"content_url"`
	CreatedAt  string `json:"created_at"`
	FileName   string `json:"file_name"`
	FileSize   int64  `json:"file_size"`
	Id         string `json:"id"`

	// IssueId 草稿附件为空串
	IssueId string `json:"issue_id"`

	// Markdown 可直接粘贴的 ![alt](content_url) 片段
	Markdown string `json:"markdown"`
	MimeType string `json:"mime_type"`
}

// IssueBatchFailure defines model for IssueBatchFailure.
type IssueBatchFailure struct {
	Error string `json:"error"`

	// Id Issue ID
	Id string `json:"id"`

	// Reference omitempty；INT-n 或 GH-n
	Reference *string `json:"reference,omitempty"`
}

// IssueBatchResult 批量操作结果，与 service.BatchCloseDoneIssuesResponse 同形；batch-close 与批量 internal-meta 共用
type IssueBatchResult struct {
	ElapsedMs int64 `json:"elapsed_ms"`
	Failed    int   `json:"failed"`

	// Failures 最多返回前 50 条失败明细
	Failures  []IssueBatchFailure `json:"failures"`
	Succeeded int                 `json:"succeeded"`
	Total     int64               `json:"total"`
}

// IssueChecklistItem defines model for IssueChecklistItem.
type IssueChecklistItem struct {
	Id          string `json:"id"`
	IsCompleted bool   `json:"is_completed"`
	SortOrder   int    `json:"sort_order"`
	Title       string `json:"title"`
}

// IssueChecklistItemInput defines model for IssueChecklistItemInput.
type IssueChecklistItemInput struct {
	// Id 缺省时服务端生成；传旧 id 复用条目
	Id          *string `json:"id,omitempty"`
	IsCompleted *bool   `json:"is_completed,omitempty"`

	// Title trim 后须非空
	Title string `json:"title"`
}

// IssueChecklistSuggestions defines model for IssueChecklistSuggestions.
type IssueChecklistSuggestions struct {
	Items []IssueChecklistSuggestions_Items `json:"items"`
}

// IssueChecklistSuggestions_Items defines model for IssueChecklistSuggestions.Items.
type IssueChecklistSuggestions_Items struct {
	Title string `json:"title"`
}

// IssueCollabArea defines model for IssueCollabArea.
type IssueCollabArea struct {
	// Consensus 未产出为 null
	Consensus *IssueCollabDoc `json:"consensus"`

	// Summary 未产出为 null
	Summary *IssueCollabDoc `json:"summary"`
}

// IssueCollabDoc defines model for IssueCollabDoc.
type IssueCollabDoc struct {
	Author    IssueCollabDoc_Author `json:"author"`
	Body      string                `json:"body"`
	CreatedAt string                `json:"created_at"`
	IssueId   string                `json:"issue_id"`
	UpdatedAt string                `json:"updated_at"`
}

// IssueCollabDoc_Author defines model for IssueCollabDoc.Author.
type IssueCollabDoc_Author struct {
	// AvatarUrl 仅 user 作者可能有值，否则空串
	AvatarUrl string           `json:"avatar_url"`
	Kind      CollabAuthorKind `json:"kind"`

	// Login agent 时为 "代理"；用户不存在时为 "未知用户"
	Login string `json:"login"`
}

// IssueComment defines model for IssueComment.
type IssueComment struct {
	Author            IssueActor `json:"author"`
	AuthorAssociation string     `json:"author_association"`
	Body              string     `json:"body"`
	BodyHtml          string     `json:"body_html"`
	CreatedAt         string     `json:"created_at"`

	// GithubCommentId internal 评论为本地合成的负值序号
	GithubCommentId int64                `json:"github_comment_id"`
	GithubNodeId    string               `json:"github_node_id"`
	HtmlUrl         string               `json:"html_url"`
	Id              string               `json:"id"`
	IssueId         string               `json:"issue_id"`
	Reactions       IssueReactionSummary `json:"reactions"`
	Source          IssueSource          `json:"source"`
	UpdatedAt       string               `json:"updated_at"`
}

// IssueFilterOptions defines model for IssueFilterOptions.
type IssueFilterOptions struct {
	Assignees  []string `json:"assignees"`
	Labels     []string `json:"labels"`
	Milestones []string `json:"milestones"`
}

// IssueGitHubMeta omitempty，仅 github 来源 Issue 出现
type IssueGitHubMeta struct {
	ActiveLockReason  string          `json:"active_lock_reason"`
	Assignees         []IssueActor    `json:"assignees"`
	AuthorAssociation string          `json:"author_association"`
	CommentsCount     int             `json:"comments_count"`
	GithubIssueId     int64           `json:"github_issue_id"`
	GithubNodeId      string          `json:"github_node_id"`
	HtmlUrl           string          `json:"html_url"`
	Labels            []IssueLabel    `json:"labels"`
	Locked            bool            `json:"locked"`
	Milestone         *IssueMilestone `json:"milestone,omitempty"`

	// Number GitHub issue 编号（reference 的 GH-n 来源）
	Number    int                  `json:"number"`
	Reactions IssueReactionSummary `json:"reactions"`
	SyncedAt  string               `json:"synced_at"`
}

// IssueInternalMeta omitempty；无 meta 且无 checklist 时整个字段缺省
type IssueInternalMeta struct {
	// Checklist omitempty；仅 Issue 详情/PUT checklist 响应携带
	Checklist      []IssueChecklistItem `json:"checklist,omitempty"`
	ChecklistDone  int                  `json:"checklist_done"`
	ChecklistTotal int                  `json:"checklist_total"`

	// ChecklistUpdatedAt omitempty；checklist 非空时的最近替换时间
	ChecklistUpdatedAt *string `json:"checklist_updated_at,omitempty"`

	// CompletedAt omitempty；首次进入 done 时写入
	CompletedAt *string `json:"completed_at,omitempty"`

	// Labels omitempty；internal issue 的标签
	Labels []IssueLabel `json:"labels,omitempty"`

	// ProgressPercent checklist 完成度 0-100；无 checklist 时为 null
	ProgressPercent *int `json:"progress_percent"`

	// StartedAt omitempty；首次进入 in_progress/done 时写入
	StartedAt *string `json:"started_at,omitempty"`

	// UpdatedAt omitempty
	UpdatedAt *string `json:"updated_at,omitempty"`

	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus IssueWorkflowStatus `json:"workflow_status"`
}

// IssueLabel defines model for IssueLabel.
type IssueLabel struct {
	// Color 十六进制颜色（不带 # 前缀）
	Color       string `json:"color"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

// IssueMilestone defines model for IssueMilestone.
type IssueMilestone struct {
	Description string `json:"description"`
	Number      int    `json:"number"`
	State       string `json:"state"`
	Title       string `json:"title"`
}

// IssuePromptItem defines model for IssuePromptItem.
type IssuePromptItem struct {
	// Content 提示词正文；trim 后非空
	Content string `json:"content"`

	// Id trim 后非空
	Id string `json:"id"`

	// Name trim 后非空
	Name string `json:"name"`

	// SupportsBatch 是否支持批量场景
	SupportsBatch *bool `json:"supports_batch,omitempty"`
}

// IssuePrompts defines model for IssuePrompts.
type IssuePrompts struct {
	// Prompts 未配置时为 null，前端兜底默认提示词
	Prompts []IssuePromptItem `json:"prompts"`
}

// IssuePullRequest defines model for IssuePullRequest.
type IssuePullRequest struct {
	AuthorLogin string  `json:"author_login"`
	BaseRef     string  `json:"base_ref"`
	ClosedAt    *string `json:"closed_at"`
	CreatedAt   string  `json:"created_at"`
	HeadRef     string  `json:"head_ref"`
	HtmlUrl     string  `json:"html_url"`
	Id          string  `json:"id"`
	IsDraft     bool    `json:"is_draft"`
	IssueId     string  `json:"issue_id"`

	// LinkOrigin manual=用户显式 attach；synced=远端同步投影产生（清理逻辑只作用于 synced）
	LinkOrigin IssuePullRequestLinkOrigin `json:"link_origin"`

	// MergedAt state=merged 时有值
	MergedAt *string `json:"merged_at"`
	Number   int     `json:"number"`

	// Provider 当前恒为 github；字段预留 gitlab
	Provider string `json:"provider"`

	// RepoFullName owner/repo；允许与项目配置的仓库不同（跨仓库 attach）
	RepoFullName string `json:"repo_full_name"`

	// State merged = GitHub 上 closed 且 merged_at 非空
	State IssuePullRequestState `json:"state"`

	// SyncedAt 最近一次从 GitHub 刷新成功的时间
	SyncedAt  string `json:"synced_at"`
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at"`
}

// IssuePullRequestLinkOrigin manual=用户显式 attach；synced=远端同步投影产生（清理逻辑只作用于 synced）
type IssuePullRequestLinkOrigin = model.IssuePullRequestLinkOrigin

// IssuePullRequestState merged = GitHub 上 closed 且 merged_at 非空
type IssuePullRequestState = model.IssuePullRequestState

// IssuePullRequestSummary Issue 关联 PR 的聚合计数；closed 计数 = total - open - merged
type IssuePullRequestSummary struct {
	// Merged state=merged 计数
	Merged int `json:"merged"`

	// Open state=open 计数
	Open  int `json:"open"`
	Total int `json:"total"`
}

// IssuePullRequestSyncFailure PR 关联刷新失败明细；失败行保留旧数据
type IssuePullRequestSyncFailure struct {
	// Error 失败原因，前缀带 repo_full_name#number 便于定位
	Error string `json:"error"`

	// Id 关联行 id（issue_pull_requests.id，detach 时用此 id）
	Id string `json:"id"`
}

// IssuePullRequestSyncResult syncIssuePullRequests 的响应形状，与批量 internal-meta 的 {items, failures} 约定一致
type IssuePullRequestSyncResult struct {
	// Failures 逐行失败明细
	Failures []IssuePullRequestSyncFailure `json:"failures"`

	// Items 本轮刷新成功的关联行（无关联或无成功时为空数组）
	Items []IssuePullRequest `json:"items"`
}

// IssueReactionSummary defines model for IssueReactionSummary.
type IssueReactionSummary struct {
	Plus1      int `json:"+1"`
	Minus1     int `json:"-1"`
	Confused   int `json:"confused"`
	Eyes       int `json:"eyes"`
	Heart      int `json:"heart"`
	Hooray     int `json:"hooray"`
	Laugh      int `json:"laugh"`
	Rocket     int `json:"rocket"`
	TotalCount int `json:"total_count"`
}

// IssueRecommendation defines model for IssueRecommendation.
type IssueRecommendation struct {
	CreatedAt string `json:"created_at"`

	// CreatedBy 提交者 API Key 名称
	CreatedBy string `json:"created_by"`

	// DeferNote 延后备注；无备注时为 null
	DeferNote *string `json:"defer_note"`

	// DeferredAt 延后时间；status=active 时为 null
	DeferredAt   *string                     `json:"deferred_at"`
	Dependencies []RecommendationDependency  `json:"dependencies"`
	Issue        RecommendationIssueSummary  `json:"issue"`
	Priority     IssueRecommendationPriority `json:"priority"`
	Reason       string                      `json:"reason"`

	// Status deferred 表示被用户延后；延后项对 Agent 不可再推荐（PUT 返回 40911）
	Status    IssueRecommendationStatus `json:"status"`
	UpdatedAt string                    `json:"updated_at"`
}

// IssueRecommendationStatus deferred 表示被用户延后；延后项对 Agent 不可再推荐（PUT 返回 40911）
type IssueRecommendationStatus string

// IssueRecommendationPriority defines model for IssueRecommendationPriority.
type IssueRecommendationPriority = model.IssueRecommendationPriority

// IssueShipHook omitempty；仅 Issue 详情/列表项中出现，未预约时缺省
type IssueShipHook struct {
	CloseEnabled bool `json:"close_enabled"`

	// CommentBody omitempty；fired 后为渲染后正文
	CommentBody    *string `json:"comment_body,omitempty"`
	CommentEnabled bool    `json:"comment_enabled"`

	// FiredAt omitempty
	FiredAt *string `json:"fired_at,omitempty"`

	// ReleaseUrl omitempty
	ReleaseUrl *string `json:"release_url,omitempty"`

	// Results omitempty；fired 后按启用的动作出现
	Results *IssueShipHookResults `json:"results,omitempty"`
	Status  IssueShipHookStatus   `json:"status"`

	// VersionId omitempty；fired 时的触发版本
	VersionId *string `json:"version_id,omitempty"`

	// VersionNumber omitempty
	VersionNumber   *string `json:"version_number,omitempty"`
	WorkflowEnabled bool    `json:"workflow_enabled"`

	// WorkflowStatus 目标工作流状态；workflow_enabled=true 且为 "" 表示重置
	WorkflowStatus string `json:"workflow_status"`
}

// IssueShipHookActionResult defines model for IssueShipHookActionResult.
type IssueShipHookActionResult struct {
	// Error omitempty
	Error *string `json:"error,omitempty"`
	Ok    bool    `json:"ok"`

	// Skipped omitempty
	Skipped *bool `json:"skipped,omitempty"`
}

// IssueShipHookResults omitempty；fired 后按启用的动作出现
type IssueShipHookResults struct {
	Close          *IssueShipHookActionResult `json:"close,omitempty"`
	Comment        *IssueShipHookActionResult `json:"comment,omitempty"`
	WorkflowStatus *IssueShipHookActionResult `json:"workflow_status,omitempty"`
}

// IssueShipHookStatus defines model for IssueShipHookStatus.
type IssueShipHookStatus = model.IssueShipHookStatus

// IssueSource defines model for IssueSource.
type IssueSource = model.IssueSource

// IssueState defines model for IssueState.
type IssueState = model.IssueState

// IssueSyncResult defines model for IssueSyncResult.
type IssueSyncResult struct {
	CompletedAt string `json:"completed_at"`

	// LastIssueUpdatedAt omitempty；本次增量水位
	LastIssueUpdatedAt  *string `json:"last_issue_updated_at,omitempty"`
	ProjectId           string  `json:"project_id"`
	StartedAt           string  `json:"started_at"`
	SyncedCommentCount  int     `json:"synced_comment_count"`
	SyncedIssueCount    int     `json:"synced_issue_count"`
	SyncedTimelineCount int     `json:"synced_timeline_count"`
}

// IssueSyncState omitempty，项目 GitHub 同步状态
type IssueSyncState struct {
	LastError string `json:"last_error"`

	// LastIssueUpdatedAt omitempty
	LastIssueUpdatedAt *string `json:"last_issue_updated_at,omitempty"`

	// LastSuccessfulSyncAt omitempty
	LastSuccessfulSyncAt *string `json:"last_successful_sync_at,omitempty"`

	// LastSyncedAt omitempty
	LastSyncedAt *string         `json:"last_synced_at,omitempty"`
	Status       IssueSyncStatus `json:"status"`
}

// IssueSyncStatus defines model for IssueSyncStatus.
type IssueSyncStatus = model.IssueSyncStatus

// IssueTimelineEvent defines model for IssueTimelineEvent.
type IssueTimelineEvent struct {
	Actor     IssueActor `json:"actor"`
	Body      string     `json:"body"`
	CreatedAt string     `json:"created_at"`
	EventKey  string     `json:"event_key"`

	// EventType GitHub 事件类型（labeled/assigned/closed/...）
	EventType     string `json:"event_type"`
	GithubEventId int64  `json:"github_event_id"`
	Id            string `json:"id"`
	IssueId       string `json:"issue_id"`

	// Payload 原始事件 JSON
	Payload map[string]interface{} `json:"payload"`

	// Summary 中文化摘要
	Summary string `json:"summary"`
}

// IssueWorkflowStatus 空串表示未设置（重置语义）
type IssueWorkflowStatus = model.IssueWorkflowStatus

// LatestVersion omitempty，仅在列表项中出现
type LatestVersion struct {
	CreatedAt     string        `json:"created_at"`
	Id            string        `json:"id"`
	Status        VersionStatus `json:"status"`
	VersionNumber string        `json:"version_number"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	CreatedAt string   `json:"created_at"`
	Id        string   `json:"id"`
	Level     LogLevel `json:"level"`
	Message   string   `json:"message"`

	// Metadata omitempty；JSON 文本（非对象）
	Metadata  *string `json:"metadata,omitempty"`
	RunId     string  `json:"run_id"`
	Source    string  `json:"source"`
	Timestamp string  `json:"timestamp"`
}

// LogEntryInput defines model for LogEntryInput.
type LogEntryInput struct {
	Level LogLevel `json:"level"`

	// Message 1-4000 字节
	Message string `json:"message"`

	// Metadata 可选 JSON 对象，序列化后 ≤4KB
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Source ≤128 字节
	Source *string `json:"source,omitempty"`

	// Timestamp 必填，不能为零值时间
	Timestamp string `json:"timestamp"`
}

// LogLevel defines model for LogLevel.
type LogLevel = model.LogLevel

// LogRun defines model for LogRun.
type LogRun struct {
	CreatedAt    string  `json:"created_at"`
	Description  string  `json:"description"`
	EntryCount   int     `json:"entry_count"`
	FirstEntryAt *string `json:"first_entry_at"`
	LastEntryAt  *string `json:"last_entry_at"`
	ProjectId    string  `json:"project_id"`
	RunId        string  `json:"run_id"`
	Source       string  `json:"source"`
	UpdatedAt    string  `json:"updated_at"`

	// UploaderApiKeyId omitempty
	UploaderApiKeyId *string `json:"uploader_api_key_id,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Login 用户名或邮箱
	Login    string `binding:"required" json:"login"`
	Password string `binding:"required" json:"password"`
}

// PaginatedData 分页响应 data 形状；与 Envelope allOf 组合后 items 由兄弟 schema 收窄为具体类型
type PaginatedData struct {
	// Items 当前页条目（元素类型由组合 schema 收窄）
	Items    []interface{} `json:"items"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// PendingIssueHook defines model for PendingIssueHook.
type PendingIssueHook struct {
	Close   bool   `json:"close"`
	Comment bool   `json:"comment"`
	IssueId string `json:"issue_id"`

	// Reference INT-n 或 GH-n
	Reference       string `json:"reference"`
	Title           string `json:"title"`
	WorkflowEnabled bool   `json:"workflow_enabled"`

	// WorkflowStatus 目标工作流状态，可能为 ""（重置）
	WorkflowStatus string `json:"workflow_status"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt   string `json:"created_at"`
	Description string `json:"description"`
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`

	// HasGithubPrToken 是否已配置独立 PR 访问 Token
	HasGithubPrToken bool   `json:"has_github_pr_token"`
	Id               string `json:"id"`

	// IssueSync omitempty，项目 GitHub 同步状态
	IssueSync *IssueSyncState `json:"issue_sync,omitempty"`

	// LatestVersion omitempty，仅在列表项中出现
	LatestVersion *LatestVersion `json:"latest_version,omitempty"`
	Name          string         `json:"name"`
	UpdatedAt     string         `json:"updated_at"`
}

// RecommendationDependency defines model for RecommendationDependency.
type RecommendationDependency struct {
	IssueId        string     `json:"issue_id"`
	ProjectId      string     `json:"project_id"`
	Reference      string     `json:"reference"`
	SequenceNumber int        `json:"sequence_number"`
	State          IssueState `json:"state"`
	Title          string     `json:"title"`

	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus IssueWorkflowStatus `json:"workflow_status"`
}

// RecommendationIssueSummary defines model for RecommendationIssueSummary.
type RecommendationIssueSummary struct {
	Id             string      `json:"id"`
	ProjectId      string      `json:"project_id"`
	ProjectName    string      `json:"project_name"`
	Reference      string      `json:"reference"`
	SequenceNumber int         `json:"sequence_number"`
	Source         IssueSource `json:"source"`
	State          IssueState  `json:"state"`
	Title          string      `json:"title"`

	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus IssueWorkflowStatus `json:"workflow_status"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken fsr_ 开头的 refresh token
	RefreshToken string `binding:"required" json:"refresh_token"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	RefreshToken string `json:"refresh_token"`
	Token        string `json:"token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email 邮箱，全局唯一
	Email string `binding:"required,email" json:"email"`

	// Password 密码，≥8 字符
	Password string `binding:"required,min=8" json:"password"`

	// Username 用户名，2-50 字符，全局唯一
	Username string `binding:"required,min=2,max=50" json:"username"`
}

// ShipCheck defines model for ShipCheck.
type ShipCheck struct {
	CanShip           bool               `json:"can_ship"`
	Items             []ShipCheckItem    `json:"items"`
	PendingIssueHooks []PendingIssueHook `json:"pending_issue_hooks"`
}

// ShipCheckItem defines model for ShipCheckItem.
type ShipCheckItem struct {
	// Detail omitempty
	Detail *string `json:"detail,omitempty"`

	// Key release_notes / artifacts / target_commitish / github_config
	Key   string `json:"key"`
	Label string `json:"label"`
	Ok    bool   `json:"ok"`
}

// ShipResult defines model for ShipResult.
type ShipResult struct {
	// HookError omitempty
	HookError  *string `json:"hook_error,omitempty"`
	HookFailed int     `json:"hook_failed"`

	// HookStatus completed / failed / incomplete
	HookStatus string `json:"hook_status"`
	HookTotal  int    `json:"hook_total"`
}

// ShipStage 空串表示未进入发货流程
type ShipStage = model.ShipStage

// ShipStatus 空串表示尚未发货（idle）
type ShipStatus = model.ShipStatus

// UpdateAISettingsRequest defines model for UpdateAISettingsRequest.
type UpdateAISettingsRequest struct {
	// ApiHost 缺省回退默认 host；须为合法 URL
	ApiHost *string `json:"api_host,omitempty"`

	// ApiKey 明文 Key（加密存储，不回显）；首次配置必填，已有配置时空串保留旧值
	ApiKey *string `json:"api_key,omitempty"`

	// Model 缺省回退默认模型
	Model *string `json:"model,omitempty"`
}

// UpdateDocumentRequest title/body/parent_id 至少传一个
type UpdateDocumentRequest struct {
	// Body ≤200000 rune
	Body *string `json:"body,omitempty"`

	// ParentId 三态：不传=不变；null=清除父级；字符串=设为父文档（须同项目且无环）
	ParentId *string `json:"parent_id,omitempty"`

	// Title trim 后 1-200 rune
	Title *string `json:"title,omitempty"`
}

// UpdateIssueRequest 至少传一个字段；state_reason 必须随 state 同传
type UpdateIssueRequest struct {
	Body *string `json:"body,omitempty"`

	// Labels 标签名数组；internal issue 须为已存在仓库标签，GitHub issue 仅做非空/去重校验
	Labels []string    `json:"labels,omitempty"`
	State  *IssueState `json:"state,omitempty"`

	// StateReason 仅 JWT；closed→completed|not_planned，open→reopened；置 open 且 reason 为空会清空
	StateReason *UpdateIssueRequestStateReason `json:"state_reason,omitempty"`

	// Title trim 后须非空
	Title *string `json:"title,omitempty"`
}

// UpdateIssueRequestStateReason 仅 JWT；closed→completed|not_planned，open→reopened；置 open 且 reason 为空会清空
type UpdateIssueRequestStateReason string

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	NewPassword string `binding:"required,min=8" json:"new_password"`
	OldPassword string `binding:"required" json:"old_password"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	// Email 新邮箱
	Email *string `json:"email,omitempty"`

	// Username 新用户名；与现值相同或省略则不变
	Username *string `json:"username,omitempty"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	// ClearGithubPrToken 为 true 时显式清除 PR 访问 Token 并恢复沿用项目 Token；与 github_pr_token 互斥，同时提供（无论取值）返回 40001
	ClearGithubPrToken *bool   `json:"clear_github_pr_token,omitempty"`
	Description        *string `json:"description,omitempty"`

	// GithubPrToken PR 访问 Token（非空时替换现值）；仅用于读取关联 PR，加密存储不回显
	GithubPrToken *string `json:"github_pr_token,omitempty"`
	GithubToken   *string `json:"github_token,omitempty"`
	Name          *string `json:"name,omitempty"`

	// RepositoryUrl 同创建；变更仓库且项目无 token 时须提供 token
	RepositoryUrl   *string `json:"repository_url,omitempty"`
	SourceProjectId *string `json:"source_project_id,omitempty"`
}

// UpdateVersionRequest defines model for UpdateVersionRequest.
type UpdateVersionRequest struct {
	ReleaseNotes *string `json:"release_notes,omitempty"`

	// TargetCommitish 非空时校验为仓库已存在分支；空串清除
	TargetCommitish *string `json:"target_commitish,omitempty"`

	// VersionNumber 仅 JWT 可改；API Key 携带返回 40301。非空且项目内唯一
	VersionNumber *string `json:"version_number,omitempty"`
}

// UploadLogsRequest defines model for UploadLogsRequest.
type UploadLogsRequest struct {
	// ChunkId 分片 ID；同 (run_id, chunk_id) 重试幂等，不要复用 chunk_id 传不同内容
	ChunkId string `json:"chunk_id"`

	// Description ≤500 字节；仅首次创建运行时写入
	Description *string         `json:"description,omitempty"`
	Entries     []LogEntryInput `json:"entries"`

	// RunId 客户端生成的运行 ID，项目内唯一
	RunId string `json:"run_id"`

	// Source ≤128 字节；仅首次创建运行时写入
	Source *string `json:"source,omitempty"`
}

// UploadLogsResult defines model for UploadLogsResult.
type UploadLogsResult struct {
	// AcceptedCount 本次实际写入条数；重复 chunk 为 0
	AcceptedCount int    `json:"accepted_count"`
	Description   string `json:"description"`

	// Duplicate (run_id, chunk_id) 重复时为 true，本次不插入
	Duplicate bool `json:"duplicate"`

	// EntryCount 该运行累计条目数
	EntryCount   int     `json:"entry_count"`
	FirstEntryAt *string `json:"first_entry_at"`
	LastEntryAt  *string `json:"last_entry_at"`
	RunId        string  `json:"run_id"`
	Source       string  `json:"source"`
}

// UpsertIssueCollabRequest defines model for UpsertIssueCollabRequest.
type UpsertIssueCollabRequest struct {
	// Body Markdown；trim 后 1-8000 rune；重复 PUT 覆盖
	Body string `json:"body"`
}

// UpsertIssueRecommendationRequest defines model for UpsertIssueRecommendationRequest.
type UpsertIssueRecommendationRequest struct {
	// Dependencies 前置依赖 Issue UUID 数组，整组替换，不含自身；重复自动去重（保序）
	Dependencies []string                     `json:"dependencies,omitempty"`
	Priority     *IssueRecommendationPriority `json:"priority,omitempty"`

	// Reason 推荐理由，trim 后 1-500 rune
	Reason string `json:"reason"`
}

// UpsertShipHookRequest 三类动作至少启用一个，否则 40001
type UpsertShipHookRequest struct {
	// Close true 时发货后关闭 Issue（state_reason=completed）
	Close *bool `json:"close,omitempty"`

	// CommentBody 传入即启用评论动作；trim 后 1-4000 rune；支持 {version}、{release_url} 占位符
	CommentBody *string `json:"comment_body,omitempty"`

	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus *IssueWorkflowStatus `json:"workflow_status,omitempty"`
}

// User defines model for User.
type User struct {
	// AvatarUrl 形如 /api/avatars/:uid/:filename，未设置为空串
	AvatarUrl string `json:"avatar_url"`
	CreatedAt string `json:"created_at"`
	Email     string `json:"email"`
	Id        string `json:"id"`
	UpdatedAt string `json:"updated_at"`
	Username  string `json:"username"`
}

// Version defines model for Version.
type Version struct {
	// Artifacts omitempty，无安装包时缺省
	Artifacts []Artifact `json:"artifacts,omitempty"`
	CreatedAt string     `json:"created_at"`
	ErrorLog  string     `json:"error_log"`

	// GithubReleaseUrl 发货成功后写入
	GithubReleaseUrl string `json:"github_release_url"`
	Id               string `json:"id"`
	ProjectId        string `json:"project_id"`
	ReleaseNotes     string `json:"release_notes"`

	// ShipHooksStatus 该次发货触发的 issue 钩子执行汇总状态
	ShipHooksStatus VersionShipHooksStatus `json:"ship_hooks_status"`
	ShipMessage     string                 `json:"ship_message"`

	// ShipStage 空串表示未进入发货流程
	ShipStage ShipStage `json:"ship_stage"`

	// ShipStatus 空串表示尚未发货（idle）
	ShipStatus      ShipStatus    `json:"ship_status"`
	ShippedAt       *string       `json:"shipped_at"`
	Status          VersionStatus `json:"status"`
	TargetCommitish string        `json:"target_commitish"`
	VersionNumber   string        `json:"version_number"`
}

// VersionShipHooksStatus 该次发货触发的 issue 钩子执行汇总状态
type VersionShipHooksStatus string

// VersionStatus defines model for VersionStatus.
type VersionStatus = model.VersionStatus

// DocId defines model for DocId.
type DocId = string

// IssueId defines model for IssueId.
type IssueId = string

// Page defines model for Page.
type Page = int

// PageSize20 defines model for PageSize20.
type PageSize20 = int

// PageSize50 defines model for PageSize50.
type PageSize50 = int

// ProjectId defines model for ProjectId.
type ProjectId = string

// ProjectOrKeyId defines model for ProjectOrKeyId.
type ProjectOrKeyId = string

// PullRequestLinkId defines model for PullRequestLinkId.
type PullRequestLinkId = string

// QueryToken defines model for QueryToken.
type QueryToken = string

// RunId defines model for RunId.
type RunId = string

// VersionId defines model for VersionId.
type VersionId = string

// BadRequest 错误响应信封
type BadRequest = ErrorEnvelope

// Conflict 错误响应信封
type Conflict = ErrorEnvelope

// EmptySuccess defines model for EmptySuccess.
type EmptySuccess struct {
	// Code 业务错误码；0 表示成功
	Code int                    `json:"code"`
	Data map[string]interface{} `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// Forbidden 错误响应信封
type Forbidden = ErrorEnvelope

// InternalError 错误响应信封
type InternalError = ErrorEnvelope

// NotFound 错误响应信封
type NotFound = ErrorEnvelope

// Unauthorized 错误响应信封
type Unauthorized = ErrorEnvelope

// GenerateIssueTitleJSONBody defines parameters for GenerateIssueTitle.
type GenerateIssueTitleJSONBody struct {
	// Body 正文内容；trim 后须 ≥10 个字符（rune），服务端截断至 10000 rune
	Body string `json:"body"`
}

// GenerateIssueTitle200JSONResponseBody defines parameters for GenerateIssueTitle.
type GenerateIssueTitle200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                    `json:"code"`
	Data *GenerateTitleResponse `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetAISettings200JSONResponseBody defines parameters for GetAISettings.
type GetAISettings200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int         `json:"code"`
	Data *AISettings `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateAISettings200JSONResponseBody defines parameters for UpdateAISettings.
type UpdateAISettings200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int         `json:"code"`
	Data *AISettings `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListApiKeys200JSONResponseBody defines parameters for ListApiKeys.
type ListApiKeys200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data []ApiKey `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CreateApiKey200JSONResponseBody defines parameters for CreateApiKey.
type CreateApiKey200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int            `json:"code"`
	Data *ApiKeyCreated `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// DownloadArtifactParams defines parameters for DownloadArtifact.
type DownloadArtifactParams struct {
	// Token 可选 query 凭证（JWT 或 `fsk_` API Key），供无法携带 Authorization 头的场景（`<img>`、浏览器直链下载）。与 Authorization 头二选一，头优先。
	Token *QueryToken `form:"token,omitempty" json:"token,omitempty"`
}

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File 图片文件，≤5MB，扩展名限 jpg/jpeg/png/gif/webp 且内容须为图片
	File openapi_types.File `json:"file"`
}

// UploadAvatar200JSONResponseBody defines parameters for UploadAvatar.
type UploadAvatar200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int   `json:"code"`
	Data *User `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// Login200JSONResponseBody defines parameters for Login.
type Login200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int           `json:"code"`
	Data *AuthResponse `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	// RefreshToken 可选，fsr_ 开头的 refresh token，传入则一并吊销
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// GetMe200JSONResponseBody defines parameters for GetMe.
type GetMe200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int   `json:"code"`
	Data *User `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateMe200JSONResponseBody defines parameters for UpdateMe.
type UpdateMe200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int   `json:"code"`
	Data *User `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// RefreshToken200JSONResponseBody defines parameters for RefreshToken.
type RefreshToken200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int              `json:"code"`
	Data *RefreshResponse `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// Register200JSONResponseBody defines parameters for Register.
type Register200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int           `json:"code"`
	Data *AuthResponse `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetAvatarParams defines parameters for GetAvatar.
type GetAvatarParams struct {
	// Token 可选 query 凭证（JWT 或 `fsk_` API Key），供无法携带 Authorization 头的场景（`<img>`、浏览器直链下载）。与 Authorization 头二选一，头优先。
	Token *QueryToken `form:"token,omitempty" json:"token,omitempty"`
}

// DashboardOverview200JSONResponseBody defines parameters for DashboardOverview.
type DashboardOverview200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                `json:"code"`
	Data *DashboardOverview `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetDocument200JSONResponseBody defines parameters for GetDocument.
type GetDocument200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int       `json:"code"`
	Data *Document `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateDocument200JSONResponseBody defines parameters for UpdateDocument.
type UpdateDocument200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int       `json:"code"`
	Data *Document `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GithubMediaProxyParams defines parameters for GithubMediaProxy.
type GithubMediaProxyParams struct {
	// Url 要代理的媒体 URL（会做 HTML unescape 与多至两次 URL decode）
	Url string `form:"url" json:"url"`

	// Token 可选 query 凭证（JWT 或 `fsk_` API Key），供无法携带 Authorization 头的场景（`<img>`、浏览器直链下载）。与 Authorization 头二选一，头优先。
	Token *QueryToken `form:"token,omitempty" json:"token,omitempty"`
}

// GithubMediaProxyHeadParams defines parameters for GithubMediaProxyHead.
type GithubMediaProxyHeadParams struct {
	// Url 要代理的媒体 URL
	Url string `form:"url" json:"url"`

	// Token 可选 query 凭证（JWT 或 `fsk_` API Key），供无法携带 Authorization 头的场景（`<img>`、浏览器直链下载）。与 Authorization 头二选一，头优先。
	Token *QueryToken `form:"token,omitempty" json:"token,omitempty"`
}

// GetIssuePrompts200JSONResponseBody defines parameters for GetIssuePrompts.
type GetIssuePrompts200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int           `json:"code"`
	Data *IssuePrompts `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateIssuePromptsJSONBody defines parameters for UpdateIssuePrompts.
type UpdateIssuePromptsJSONBody struct {
	Prompts []IssuePromptItem `json:"prompts"`
}

// UpdateIssuePrompts200JSONResponseBody defines parameters for UpdateIssuePrompts.
type UpdateIssuePrompts200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int           `json:"code"`
	Data *IssuePrompts `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetIssueAssetContentParams defines parameters for GetIssueAssetContent.
type GetIssueAssetContentParams struct {
	// Token 可选 query 凭证（JWT 或 `fsk_` API Key），供无法携带 Authorization 头的场景（`<img>`、浏览器直链下载）。与 Authorization 头二选一，头优先。
	Token *QueryToken `form:"token,omitempty" json:"token,omitempty"`
}

// GetIssueAssetContentHeadParams defines parameters for GetIssueAssetContentHead.
type GetIssueAssetContentHeadParams struct {
	// Token 可选 query 凭证（JWT 或 `fsk_` API Key），供无法携带 Authorization 头的场景（`<img>`、浏览器直链下载）。与 Authorization 头二选一，头优先。
	Token *QueryToken `form:"token,omitempty" json:"token,omitempty"`
}

// BatchUpdateIssueInternalMetaJSONBody defines parameters for BatchUpdateIssueInternalMeta.
type BatchUpdateIssueInternalMetaJSONBody struct {
	Items []BatchUpdateIssueInternalMetaJSONBody_Items `json:"items"`
}

// BatchUpdateIssueInternalMetaJSONBody_Items defines parameters for BatchUpdateIssueInternalMeta.
type BatchUpdateIssueInternalMetaJSONBody_Items struct {
	// IssueId Issue ID（UUID）
	IssueId string `json:"issue_id"`

	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus *IssueWorkflowStatus `json:"workflow_status,omitempty"`
}

// BatchUpdateIssueInternalMeta200JSONResponseBody defines parameters for BatchUpdateIssueInternalMeta.
type BatchUpdateIssueInternalMeta200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data 批量操作结果，与 service.BatchCloseDoneIssuesResponse 同形；batch-close 与批量 internal-meta 共用
	Data *IssueBatchResult `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetIssue200JSONResponseBody defines parameters for GetIssue.
type GetIssue200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int    `json:"code"`
	Data *Issue `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateIssue200JSONResponseBody defines parameters for UpdateIssue.
type UpdateIssue200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int    `json:"code"`
	Data *Issue `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UploadIssueAssetMultipartBody defines parameters for UploadIssueAsset.
type UploadIssueAssetMultipartBody struct {
	// File 图片文件；内容须为 image/*
	File openapi_types.File `json:"file"`
}

// UploadIssueAsset200JSONResponseBody defines parameters for UploadIssueAsset.
type UploadIssueAsset200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int         `json:"code"`
	Data *IssueAsset `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ReplaceIssueChecklistJSONBody defines parameters for ReplaceIssueChecklist.
type ReplaceIssueChecklistJSONBody struct {
	Items []IssueChecklistItemInput `binding:"required" json:"items"`
}

// ReplaceIssueChecklist200JSONResponseBody defines parameters for ReplaceIssueChecklist.
type ReplaceIssueChecklist200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data omitempty；无 meta 且无 checklist 时整个字段缺省
	Data *IssueInternalMeta `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// SuggestIssueChecklist200JSONResponseBody defines parameters for SuggestIssueChecklist.
type SuggestIssueChecklist200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                        `json:"code"`
	Data *IssueChecklistSuggestions `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetIssueCollabArea200JSONResponseBody defines parameters for GetIssueCollabArea.
type GetIssueCollabArea200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int              `json:"code"`
	Data *IssueCollabArea `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpsertCollabConsensus200JSONResponseBody defines parameters for UpsertCollabConsensus.
type UpsertCollabConsensus200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int             `json:"code"`
	Data *IssueCollabDoc `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpsertCollabSummary200JSONResponseBody defines parameters for UpsertCollabSummary.
type UpsertCollabSummary200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int             `json:"code"`
	Data *IssueCollabDoc `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListIssueCommentsParams defines parameters for ListIssueComments.
type ListIssueCommentsParams struct {
	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 50
	PageSize *PageSize50 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListIssueComments200JSONResponseBody_Data defines parameters for ListIssueComments.
type ListIssueComments200JSONResponseBody_Data struct {
	Items    []IssueComment `json:"items"`
	Page     int            `json:"page"`
	PageSize int            `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListIssueComments200JSONResponseBody defines parameters for ListIssueComments.
type ListIssueComments200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                        `json:"code"`
	Data *ListIssueComments200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CreateIssueCommentJSONBody defines parameters for CreateIssueComment.
type CreateIssueCommentJSONBody struct {
	// Body 评论正文；trim 后须非空
	Body string `json:"body"`
}

// CreateIssueComment200JSONResponseBody defines parameters for CreateIssueComment.
type CreateIssueComment200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int           `json:"code"`
	Data *IssueComment `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateIssueInternalMetaJSONBody defines parameters for UpdateIssueInternalMeta.
type UpdateIssueInternalMetaJSONBody struct {
	// WorkflowStatus 空串表示未设置（重置语义）
	WorkflowStatus *IssueWorkflowStatus `json:"workflow_status,omitempty"`
}

// UpdateIssueInternalMeta200JSONResponseBody defines parameters for UpdateIssueInternalMeta.
type UpdateIssueInternalMeta200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data omitempty；无 meta 且无 checklist 时整个字段缺省
	Data *IssueInternalMeta `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// AttachIssuePullRequest200JSONResponseBody defines parameters for AttachIssuePullRequest.
type AttachIssuePullRequest200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int               `json:"code"`
	Data *IssuePullRequest `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// SyncIssuePullRequests200JSONResponseBody defines parameters for SyncIssuePullRequests.
type SyncIssuePullRequests200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data syncIssuePullRequests 的响应形状，与批量 internal-meta 的 {items, failures} 约定一致
	Data *IssuePullRequestSyncResult `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpsertIssueRecommendation200JSONResponseBody defines parameters for UpsertIssueRecommendation.
type UpsertIssueRecommendation200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                  `json:"code"`
	Data *IssueRecommendation `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// RestoreIssueRecommendation200JSONResponseBody defines parameters for RestoreIssueRecommendation.
type RestoreIssueRecommendation200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                  `json:"code"`
	Data *IssueRecommendation `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// DeferIssueRecommendation200JSONResponseBody defines parameters for DeferIssueRecommendation.
type DeferIssueRecommendation200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                  `json:"code"`
	Data *IssueRecommendation `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpsertShipHook200JSONResponseBody defines parameters for UpsertShipHook.
type UpsertShipHook200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data omitempty；仅 Issue 详情/列表项中出现，未预约时缺省
	Data *IssueShipHook `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListIssueTimelineParams defines parameters for ListIssueTimeline.
type ListIssueTimelineParams struct {
	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 50
	PageSize *PageSize50 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListIssueTimeline200JSONResponseBody_Data defines parameters for ListIssueTimeline.
type ListIssueTimeline200JSONResponseBody_Data struct {
	Items    []IssueTimelineEvent `json:"items"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListIssueTimeline200JSONResponseBody defines parameters for ListIssueTimeline.
type ListIssueTimeline200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                        `json:"code"`
	Data *ListIssueTimeline200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 20
	PageSize *PageSize20 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListProjects200JSONResponseBody_Data defines parameters for ListProjects.
type ListProjects200JSONResponseBody_Data struct {
	Items    []Project `json:"items"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListProjects200JSONResponseBody defines parameters for ListProjects.
type ListProjects200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                   `json:"code"`
	Data *ListProjects200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CreateProject200JSONResponseBody defines parameters for CreateProject.
type CreateProject200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data *Project `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetProject200JSONResponseBody defines parameters for GetProject.
type GetProject200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data *Project `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateProject200JSONResponseBody defines parameters for UpdateProject.
type UpdateProject200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data *Project `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetProjectBranches200JSONResponseBody_Data defines parameters for GetProjectBranches.
type GetProjectBranches200JSONResponseBody_Data struct {
	Branches      []Branch `json:"branches"`
	DefaultBranch string   `json:"default_branch"`
}

// GetProjectBranches200JSONResponseBody defines parameters for GetProjectBranches.
type GetProjectBranches200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                         `json:"code"`
	Data *GetProjectBranches200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListDocuments200JSONResponseBody_Data defines parameters for ListDocuments.
type ListDocuments200JSONResponseBody_Data struct {
	Items []DocumentListItem `json:"items"`
	Total int64              `json:"total"`
}

// ListDocuments200JSONResponseBody defines parameters for ListDocuments.
type ListDocuments200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                    `json:"code"`
	Data *ListDocuments200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CreateDocument200JSONResponseBody defines parameters for CreateDocument.
type CreateDocument200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int       `json:"code"`
	Data *Document `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListIssuesParams defines parameters for ListIssues.
type ListIssuesParams struct {
	// State 按 open/closed 过滤
	State *IssueState `form:"state,omitempty" json:"state,omitempty"`

	// Q 关键词过滤（内存全量匹配）：匹配标题、正文、作者 login、`INT-123`/`GH-123` 编号，纯数字时还会匹配 sequence_number 或 GitHub number
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Label 按标签名过滤（不区分大小写；GitHub 标签与 internal-meta 标签均匹配）
	Label *string `form:"label,omitempty" json:"label,omitempty"`

	// Source 按来源过滤
	Source *IssueSource `form:"source,omitempty" json:"source,omitempty"`

	// Assignee 按 GitHub 指派人 login 过滤（不区分大小写）
	Assignee *string `form:"assignee,omitempty" json:"assignee,omitempty"`

	// Milestone 按 GitHub 里程碑标题过滤（不区分大小写）
	Milestone *string `form:"milestone,omitempty" json:"milestone,omitempty"`

	// WorkflowStatus 按工作流状态过滤；`unset` 表示未设置（无 meta 或为空串）
	WorkflowStatus *ListIssuesParamsWorkflowStatus `form:"workflow_status,omitempty" json:"workflow_status,omitempty"`

	// Sort 排序；未知值按 updated_desc 处理
	Sort *ListIssuesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 20
	PageSize *PageSize20 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListIssuesParamsWorkflowStatus defines parameters for ListIssues.
type ListIssuesParamsWorkflowStatus string

// ListIssuesParamsSort defines parameters for ListIssues.
type ListIssuesParamsSort string

// ListIssues200JSONResponseBody_Data defines parameters for ListIssues.
type ListIssues200JSONResponseBody_Data struct {
	Items    []Issue `json:"items"`
	Page     int     `json:"page"`
	PageSize int     `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListIssues200JSONResponseBody defines parameters for ListIssues.
type ListIssues200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                 `json:"code"`
	Data *ListIssues200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CreateIssue200JSONResponseBody defines parameters for CreateIssue.
type CreateIssue200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int    `json:"code"`
	Data *Issue `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UploadDraftIssueAssetMultipartBody defines parameters for UploadDraftIssueAsset.
type UploadDraftIssueAssetMultipartBody struct {
	// File 图片文件；内容须为 image/*
	File openapi_types.File `json:"file"`
}

// UploadDraftIssueAsset200JSONResponseBody defines parameters for UploadDraftIssueAsset.
type UploadDraftIssueAsset200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int         `json:"code"`
	Data *IssueAsset `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// BatchCloseDoneIssuesJSONBody defines parameters for BatchCloseDoneIssues.
type BatchCloseDoneIssuesJSONBody struct {
	Source *IssueSource `json:"source,omitempty"`
}

// BatchCloseDoneIssues200JSONResponseBody defines parameters for BatchCloseDoneIssues.
type BatchCloseDoneIssues200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int `json:"code"`

	// Data 批量操作结果，与 service.BatchCloseDoneIssuesResponse 同形；batch-close 与批量 internal-meta 共用
	Data *IssueBatchResult `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CountIssuesParams defines parameters for CountIssues.
type CountIssuesParams struct {
	State *IssueState `form:"state,omitempty" json:"state,omitempty"`

	// Q 同 listIssues 的 q：标题/正文/作者/编号/纯数字序号
	Q              *string                          `form:"q,omitempty" json:"q,omitempty"`
	Label          *string                          `form:"label,omitempty" json:"label,omitempty"`
	Source         *IssueSource                     `form:"source,omitempty" json:"source,omitempty"`
	Assignee       *string                          `form:"assignee,omitempty" json:"assignee,omitempty"`
	Milestone      *string                          `form:"milestone,omitempty" json:"milestone,omitempty"`
	WorkflowStatus *CountIssuesParamsWorkflowStatus `form:"workflow_status,omitempty" json:"workflow_status,omitempty"`

	// Sort 接受但忽略（计数不排序）
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// CountIssuesParamsWorkflowStatus defines parameters for CountIssues.
type CountIssuesParamsWorkflowStatus string

// CountIssues200JSONResponseBody_Data defines parameters for CountIssues.
type CountIssues200JSONResponseBody_Data struct {
	Count int64 `json:"count"`
}

// CountIssues200JSONResponseBody defines parameters for CountIssues.
type CountIssues200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                  `json:"code"`
	Data *CountIssues200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// IssueFilterOptions200JSONResponseBody defines parameters for IssueFilterOptions.
type IssueFilterOptions200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                 `json:"code"`
	Data *IssueFilterOptions `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// IssueRepoLabels200JSONResponseBody defines parameters for IssueRepoLabels.
type IssueRepoLabels200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int          `json:"code"`
	Data []IssueLabel `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// SyncIssues200JSONResponseBody defines parameters for SyncIssues.
type SyncIssues200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int              `json:"code"`
	Data *IssueSyncResult `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListLogRunsParams defines parameters for ListLogRuns.
type ListLogRunsParams struct {
	// RunId 按运行 ID 过滤
	RunId *string `form:"run_id,omitempty" json:"run_id,omitempty"`

	// Source 按运行 source 过滤
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// From 起始时间（RFC3339），按运行创建时间过滤
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To 结束时间（RFC3339）
	To *string `form:"to,omitempty" json:"to,omitempty"`

	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 50
	PageSize *PageSize50 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListLogRuns200JSONResponseBody_Data defines parameters for ListLogRuns.
type ListLogRuns200JSONResponseBody_Data struct {
	Items    []LogRun `json:"items"`
	Page     int      `json:"page"`
	PageSize int      `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListLogRuns200JSONResponseBody defines parameters for ListLogRuns.
type ListLogRuns200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                  `json:"code"`
	Data *ListLogRuns200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetLogRun200JSONResponseBody defines parameters for GetLogRun.
type GetLogRun200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int     `json:"code"`
	Data *LogRun `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListLogEntriesParams defines parameters for ListLogEntries.
type ListLogEntriesParams struct {
	// RunId 按运行 ID 过滤
	RunId *string `form:"run_id,omitempty" json:"run_id,omitempty"`

	// Level 按日志级别过滤
	Level *LogLevel `form:"level,omitempty" json:"level,omitempty"`

	// EntrySource 按条目 source 过滤
	EntrySource *string `form:"entry_source,omitempty" json:"entry_source,omitempty"`

	// Q 按 message 内容过滤
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// From 起始时间（RFC3339），按条目 timestamp 过滤
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To 结束时间（RFC3339）
	To *string `form:"to,omitempty" json:"to,omitempty"`

	// Sort 排序；非法值返回 40001
	Sort *ListLogEntriesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 50
	PageSize *PageSize50 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListLogEntriesParamsSort defines parameters for ListLogEntries.
type ListLogEntriesParamsSort string

// ListLogEntries200JSONResponseBody_Data defines parameters for ListLogEntries.
type ListLogEntries200JSONResponseBody_Data struct {
	Items    []LogEntry `json:"items"`
	Page     int        `json:"page"`
	PageSize int        `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListLogEntries200JSONResponseBody defines parameters for ListLogEntries.
type ListLogEntries200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                     `json:"code"`
	Data *ListLogEntries200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UploadLogs200JSONResponseBody defines parameters for UploadLogs.
type UploadLogs200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int               `json:"code"`
	Data *UploadLogsResult `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListVersionsParams defines parameters for ListVersions.
type ListVersionsParams struct {
	// Status 按版本状态过滤
	Status *VersionStatus `form:"status,omitempty" json:"status,omitempty"`

	// Page 页码，<1 按 1 处理
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页条数；越界（<1 或 >100）回落为 20
	PageSize *PageSize20 `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListVersions200JSONResponseBody_Data defines parameters for ListVersions.
type ListVersions200JSONResponseBody_Data struct {
	Items    []Version `json:"items"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`

	// Total 符合条件的总条数
	Total int64 `json:"total"`
}

// ListVersions200JSONResponseBody defines parameters for ListVersions.
type ListVersions200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                   `json:"code"`
	Data *ListVersions200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// CreateVersion200JSONResponseBody defines parameters for CreateVersion.
type CreateVersion200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data *Version `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ListIssueRecommendationsParams defines parameters for ListIssueRecommendations.
type ListIssueRecommendationsParams struct {
	// ProjectId 项目 ID；缺省返回当前用户全部项目的推荐
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// ListIssueRecommendations200JSONResponseBody_Data defines parameters for ListIssueRecommendations.
type ListIssueRecommendations200JSONResponseBody_Data struct {
	Items []IssueRecommendation `json:"items"`
}

// ListIssueRecommendations200JSONResponseBody defines parameters for ListIssueRecommendations.
type ListIssueRecommendations200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int                                               `json:"code"`
	Data *ListIssueRecommendations200JSONResponseBody_Data `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GetVersion200JSONResponseBody defines parameters for GetVersion.
type GetVersion200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data *Version `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UpdateVersion200JSONResponseBody defines parameters for UpdateVersion.
type UpdateVersion200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int      `json:"code"`
	Data *Version `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// UploadArtifactMultipartBody defines parameters for UploadArtifact.
type UploadArtifactMultipartBody struct {
	// File 安装包文件
	File openapi_types.File `json:"file"`

	// Platform 可选平台标识，如 darwin-arm64、linux-amd64
	Platform *string `json:"platform,omitempty"`
}

// UploadArtifact200JSONResponseBody defines parameters for UploadArtifact.
type UploadArtifact200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int       `json:"code"`
	Data *Artifact `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ShipVersion200JSONResponseBody defines parameters for ShipVersion.
type ShipVersion200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int         `json:"code"`
	Data *ShipResult `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// ShipCheck200JSONResponseBody defines parameters for ShipCheck.
type ShipCheck200JSONResponseBody struct {
	// Code 业务错误码；0 表示成功
	Code int        `json:"code"`
	Data *ShipCheck `json:"data,omitempty"`

	// Message 人类可读信息；成功时为 "success"
	Message string `json:"message"`
}

// GenerateIssueTitleJSONRequestBody defines body for GenerateIssueTitle for application/json ContentType.
type GenerateIssueTitleJSONRequestBody GenerateIssueTitleJSONBody

// UpdateAISettingsJSONRequestBody defines body for UpdateAISettings for application/json ContentType.
type UpdateAISettingsJSONRequestBody = UpdateAISettingsRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody = UpdatePasswordRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpdateDocumentJSONRequestBody defines body for UpdateDocument for application/json ContentType.
type UpdateDocumentJSONRequestBody = UpdateDocumentRequest

// UpdateIssuePromptsJSONRequestBody defines body for UpdateIssuePrompts for application/json ContentType.
type UpdateIssuePromptsJSONRequestBody UpdateIssuePromptsJSONBody

// BatchUpdateIssueInternalMetaJSONRequestBody defines body for BatchUpdateIssueInternalMeta for application/json ContentType.
type BatchUpdateIssueInternalMetaJSONRequestBody BatchUpdateIssueInternalMetaJSONBody

// UpdateIssueJSONRequestBody defines body for UpdateIssue for application/json ContentType.
type UpdateIssueJSONRequestBody = UpdateIssueRequest

// UploadIssueAssetMultipartRequestBody defines body for UploadIssueAsset for multipart/form-data ContentType.
type UploadIssueAssetMultipartRequestBody UploadIssueAssetMultipartBody

// ReplaceIssueChecklistJSONRequestBody defines body for ReplaceIssueChecklist for application/json ContentType.
type ReplaceIssueChecklistJSONRequestBody ReplaceIssueChecklistJSONBody

// UpsertCollabConsensusJSONRequestBody defines body for UpsertCollabConsensus for application/json ContentType.
type UpsertCollabConsensusJSONRequestBody = UpsertIssueCollabRequest

// UpsertCollabSummaryJSONRequestBody defines body for UpsertCollabSummary for application/json ContentType.
type UpsertCollabSummaryJSONRequestBody = UpsertIssueCollabRequest

// CreateIssueCommentJSONRequestBody defines body for CreateIssueComment for application/json ContentType.
type CreateIssueCommentJSONRequestBody CreateIssueCommentJSONBody

// UpdateIssueInternalMetaJSONRequestBody defines body for UpdateIssueInternalMeta for application/json ContentType.
type UpdateIssueInternalMetaJSONRequestBody UpdateIssueInternalMetaJSONBody

// AttachIssuePullRequestJSONRequestBody defines body for AttachIssuePullRequest for application/json ContentType.
type AttachIssuePullRequestJSONRequestBody = AttachIssuePullRequestRequest

// UpsertIssueRecommendationJSONRequestBody defines body for UpsertIssueRecommendation for application/json ContentType.
type UpsertIssueRecommendationJSONRequestBody = UpsertIssueRecommendationRequest

// DeferIssueRecommendationJSONRequestBody defines body for DeferIssueRecommendation for application/json ContentType.
type DeferIssueRecommendationJSONRequestBody = DeferIssueRecommendationRequest

// UpsertShipHookJSONRequestBody defines body for UpsertShipHook for application/json ContentType.
type UpsertShipHookJSONRequestBody = UpsertShipHookRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// CreateIssueJSONRequestBody defines body for CreateIssue for application/json ContentType.
type CreateIssueJSONRequestBody = CreateIssueRequest

// UploadDraftIssueAssetMultipartRequestBody defines body for UploadDraftIssueAsset for multipart/form-data ContentType.
type UploadDraftIssueAssetMultipartRequestBody UploadDraftIssueAssetMultipartBody

// BatchCloseDoneIssuesJSONRequestBody defines body for BatchCloseDoneIssues for application/json ContentType.
type BatchCloseDoneIssuesJSONRequestBody BatchCloseDoneIssuesJSONBody

// UploadLogsJSONRequestBody defines body for UploadLogs for application/json ContentType.
type UploadLogsJSONRequestBody = UploadLogsRequest

// CreateVersionJSONRequestBody defines body for CreateVersion for application/json ContentType.
type CreateVersionJSONRequestBody = CreateVersionRequest

// UpdateVersionJSONRequestBody defines body for UpdateVersion for application/json ContentType.
type UpdateVersionJSONRequestBody = UpdateVersionRequest

// UploadArtifactMultipartRequestBody defines body for UploadArtifact for multipart/form-data ContentType.
type UploadArtifactMultipartRequestBody UploadArtifactMultipartBody
